"""add_profile_user_id_unique

Revision ID: 54bbb74ac54f
Revises: b0773fae636b
Create Date: 2026-07-14 07:38:55.039972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '54bbb74ac54f'
down_revision: Union[str, None] = 'b0773fae636b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'profile', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profile', type_='unique')
    # ### end Alembic commands ###
